exit if wrong runner is selected

diff --git a/build-snap/action.yml b/build-snap/action.yml
--- a/build-snap/action.yml
+++ b/build-snap/action.yml
@@ -34,6 +34,12 @@ runs:
   steps:
 
     - run: |
+        if [ "$RUNNER_OS" != "Linux" ]; then
+          echo "::error::wrong OS, please select runs-on: ubuntu-latest" && exit 1
+        fi
+      shell: bash
+      
+    - run: |
         sudo snap install snapcraft --classic
         sudo dpkg --add-architecture arm64
         echo "deb [arch=arm64] http://ports.ubuntu.com/ focal main restricted universe" | sudo tee -a /etc/apt/sources.list.d/multiarch-libs.list
diff --git a/validate-json-schema/action.yml b/validate-json-schema/action.yml
--- a/validate-json-schema/action.yml
+++ b/validate-json-schema/action.yml
@@ -42,6 +42,12 @@ runs:
   steps:
 
     - run: |
+        if [ "$RUNNER_OS" != "Linux" ]; then
+          echo "::error::wrong OS, please select runs-on: ubuntu-latest" && exit 1
+        fi
+      shell: bash
+      
+    - run: |
         url=https://github.com/boschrexroth/json-schema/tree/master/ctrlx-automation/ctrlx-core/apps/package-manifest
         link="$url"/"${{ inputs.json-schema }}"
       
